"""add file_manager related tables

Revision ID: 073c5cbbc105
Revises: 1466df05ac01
Create Date: 2025-12-10 11:34:56.043906
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '073c5cbbc105'
down_revision = '1466df05ac01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_master',
    sa.Column('account_uid', sa.Uuid(), nullable=True),
    sa.Column('accounts_id', sa.Text(), nullable=True),
    sa.Column('entity_uid', sa.Uuid(), nullable=True),
    sa.Column('firm_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('frequency', sa.Text(), nullable=True),
    sa.Column('delay', sa.Integer(), nullable=True),
    sa.Column('annual_delay', sa.Integer(), nullable=True),
    sa.Column('firm_name', sa.Text(), nullable=True),
    sa.Column('entity_name', sa.Text(), nullable=True),
    sa.Column('account_name', sa.Text(), nullable=True),
    sa.Column('investor', sa.Text(), nullable=True),
    sa.Column('tokenized_account_name', sa.Text(), nullable=True),
    sa.Column('tokenized_investor', sa.Text(), nullable=True),
    sa.Column('reason_for_toggle', sa.Text(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('account_status', sa.Text(), nullable=True),
    sa.Column('account_status_date', sa.DateTime(), nullable=True),
    sa.Column('source_uid', sa.Uuid(), nullable=True),
    sa.Column('institution_name', sa.Text(), nullable=True),
    sa.Column('manager_type', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extract_file',
    sa.Column('doc_uid', sa.Uuid(), nullable=False),
    sa.Column('document_configuration_id', sa.Uuid(), nullable=True),
    sa.Column('document_type', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.Text(), nullable=True),
    sa.Column('investor', sa.Text(), nullable=True),
    sa.Column('account', sa.Text(), nullable=True),
    sa.Column('account_uid', sa.Uuid(), nullable=True),
    sa.Column('account_sid', sa.Text(), nullable=True),
    sa.Column('firm_id', sa.Integer(), nullable=True),
    sa.Column('entity_uid', sa.Uuid(), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('ingestion_token', sa.Text(), nullable=True),
    sa.Column('business_date', sa.Date(), nullable=True),
    sa.Column('is_linked', sa.Boolean(), nullable=False),
    sa.Column('is_ignored', sa.Boolean(), nullable=False),
    sa.Column('ignore_comment', sa.Text(), nullable=True),
    sa.Column('batch_id', sa.Text(), nullable=True),
    sa.Column('ingestion_status', sa.String(length=10), nullable=True),
    sa.Column('ingestion_log', sa.Text(), nullable=True),
    sa.Column('is_manual_ingested', sa.Boolean(), nullable=True),
    sa.Column('ingested_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_configuration',
    sa.Column('configuration_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sla_priority', sa.Integer(), nullable=True),
    sa.Column('sla_days', sa.Integer(), nullable=True),
    sa.Column('schema_type', sa.String(length=50), nullable=False),
    sa.Column('extraction', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('document_type_id', sa.Uuid(), nullable=True),
    sa.Column('ingestion_code', sa.Integer(), nullable=True),
    sa.Column('field_type', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firm_master',
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('firm_parent_id', sa.Integer(), nullable=True),
    sa.Column('partner_client_id', sa.Integer(), nullable=True),
    sa.Column('system', sa.String(length=50), nullable=True),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publishing_control',
    sa.Column('account_uid', sa.Uuid(), nullable=True),
    sa.Column('business_date', sa.Date(), nullable=True),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('document_type', sa.Text(), nullable=True),
    sa.Column('pub_status', sa.Text(), nullable=True),
    sa.Column('delay', sa.Integer(), nullable=True),
    sa.Column('annual_delay', sa.Integer(), nullable=True),
    sa.Column('pub_id', sa.Uuid(), nullable=True),
    sa.Column('frequency', sa.Text(), nullable=True),
    sa.Column('change_type', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Drop CUST_FEEDS_CONFIG only if it exists
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if insp.has_table('CUST_FEEDS_CONFIG'):
        op.drop_table('CUST_FEEDS_CONFIG')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CUST_FEEDS_CONFIG',
    sa.Column('IdNmb', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('FeedId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('FeedToken', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('DownloadFolder', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('PositionFolder', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('TransactionFolder', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ProcessFolder', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('AccountFolder', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('SecurityFolder', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('PriceFolder', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('TaxLotFolder', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('PositionFileName', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('TransactionFileName', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('AccountFileName', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('SecurityFileName', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('PriceFileName', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('BalanceFileName', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('TaxLotFileName', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('UseCustodianTransactionId', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('UsePositionFileForPrices', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('EmailNotificationList', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('OFXFeed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('Inactive', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('Comment', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('CreateUser', sa.VARCHAR(length=35), server_default=sa.text('CURRENT_USER'), autoincrement=False, nullable=False),
    sa.Column('CreateDate', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('DeleteUser', sa.VARCHAR(length=35), autoincrement=False, nullable=True),
    sa.Column('DeleteDate', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('UseLocalNotBase', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('MakeAccruedInterest', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('MakeTaxWithheld', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('User1FileName', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('User1ConfigName', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('User2FileName', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('User2ConfigName', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('User3FileName', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('User3ConfigName', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('User4FileName', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('User4ConfigName', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('User5FileName', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('User5ConfigName', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('User6FileName', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('User6ConfigName', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('FeedId', 'Inactive', name=op.f('CUST_FEEDS_CONFIG_pkey'))
    )
    op.drop_table('publishing_control')
    op.drop_table('firm_master')
    op.drop_table('file_configuration')
    op.drop_table('extract_file')
    op.drop_table('account_master')
    # ### end Alembic commands ###
