"""Update level Datatype

Revision ID: 1466df05ac01
Revises: 3bd2f9965e9b
Create Date: 2025-12-09 18:27:55.342883
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1466df05ac01'
down_revision = '3bd2f9965e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'level',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'level',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
