"""Initial Migration

Revision ID: 3bd2f9965e9b
Revises: 
Create Date: 2025-12-09 15:33:29.448017
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3bd2f9965e9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('doc_uid', sa.Uuid(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('firm', sa.Integer(), nullable=True),
    sa.Column('entity_uid', sa.Uuid(), nullable=True),
    sa.Column('account_sid', sa.String(), nullable=True),
    sa.Column('account_uid', sa.Uuid(), nullable=True),
    sa.Column('position_uid', sa.Uuid(), nullable=True),
    sa.Column('report_date', sa.String(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('module', sa.String(), nullable=True),
    sa.Column('work_sid', sa.String(), nullable=True),
    sa.Column('work_uid', sa.Uuid(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('create_by', sa.String(), nullable=True),
    sa.Column('client_entity_uid', sa.Uuid(), nullable=True),
    sa.Column('filename_alt', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('pub_uid', sa.Uuid(), nullable=True),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('status_date', sa.DateTime(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('doc_sid', sa.String(), nullable=True),
    sa.Column('link_uid', sa.Uuid(), nullable=True),
    sa.Column('available_date', sa.DateTime(), nullable=True),
    sa.Column('notice_date', sa.DateTime(), nullable=True),
    sa.Column('reason_id', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('harvest_system', sa.String(), nullable=True),
    sa.Column('harvest_method', sa.String(), nullable=True),
    sa.Column('harvest_source', sa.String(), nullable=True),
    sa.Column('index_system', sa.String(), nullable=True),
    sa.Column('index_method', sa.String(), nullable=True),
    sa.Column('extract_system', sa.String(), nullable=True),
    sa.Column('extract_method', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('email_sender', sa.String(), nullable=True),
    sa.Column('email_subject', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('failure_stage', sa.String(), nullable=True),
    sa.Column('document_type_procees_rule', sa.String(), nullable=True),
    sa.Column('document_type_gen_ai', sa.String(), nullable=True),
    sa.Column('ignored_on', sa.DateTime(), nullable=True),
    sa.Column('ignored_by', sa.String(), nullable=True),
    sa.Column('rule', sa.String(), nullable=True),
    sa.Column('business_date', sa.DateTime(), nullable=True),
    sa.Column('firm_name', sa.String(), nullable=True),
    sa.Column('entity_name', sa.String(), nullable=True),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('capture_method', sa.String(), nullable=True),
    sa.Column('capture_system', sa.String(), nullable=True),
    sa.Column('linking_method', sa.String(), nullable=True),
    sa.Column('linking_system', sa.String(), nullable=True),
    sa.Column('source_attributes', sa.String(), nullable=True),
    sa.Column('investor', sa.String(), nullable=True),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=450), nullable=True),
    sa.Column('duplicate_document_id', sa.Uuid(), nullable=True),
    sa.Column('update_document_id', sa.Uuid(), nullable=True),
    sa.Column('status_comment', sa.String(), nullable=True),
    sa.Column('document_process_stage', sa.String(), nullable=True),
    sa.Column('business_rule_applied_date', sa.DateTime(), nullable=True),
    sa.Column('file_extension', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('group_code', sa.String(), nullable=True),
    sa.Column('last_attempted_time', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('replay', sa.Boolean(), nullable=True),
    sa.Column('ingestion_failed_image_url', sa.String(length=250), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('message_template', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exception', sa.Text(), nullable=True),
    sa.Column('log_event', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    op.drop_table('file')
    # ### end Alembic commands ###
